#!/bin/bash

host=$1
sleep=${2:-1}
show=${3:-0}
name=${4:-""}

full_name=$host
if [ -n "$name" ]; then
full_name="${name} ${host}"
fi

if [ -z $host ]; then
echo "Usage: `basename $0` [HOST]"
exit 1
fi

while :; do
result=`ping -W 1 -c 1 $host | grep 'bytes from '`
if [ $? -gt 0 ]; then
   echo -e "`date +'%Y/%m/%d %H:%M:%S'` - $full_name is \033[0;31mdown\033[0m"
else
   if [ $show -eq 0 ]; then
      echo -e "`date +'%Y/%m/%d %H:%M:%S'` - $full_name is \033[0;32mok\033[0m -`echo $result | cut -d ':' -f 2`"
   fi
   sleep $sleep # avoid ping rain
fi
done
